spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://test
    username: root
    password: test
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5

logging:
  level:
    root: DEBUG