spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/app
    username: postgres
    password: 1234
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5

logging:
  level:
   root: DEBUG