--CREATE USER 'postgre'@'localhost' IDENTIFIED BY '1234';

--CREATE DATABASE app;

--GRANT ALL PRIVILEGES ON app.* TO 'postgree'@'localhost';

--FLUSH PRIVILEGES;

DROP ALL OBJECTS;
DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS courses;
DROP TABLE IF EXISTS groups;
DROP TABLE IF EXISTS groups_courses;
DROP TABLE IF EXISTS students_courses;